apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-{{ .Release.Namespace }}
type: Opaque
data:
  rootPassword: cGFzc3dvcmQ= # password
  user: c2Fub3U=  # sanou
  password: cGFzc3dvcmQ= # password
