CREATE USER IF NOT EXISTS 'gil'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON DST_AIRLINES.* TO 'gil'@'%';
FLUSH PRIVILEGES;

CREATE USER IF NOT EXISTS 'bruno'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON DST_AIRLINES.* TO 'bruno'@'%';
FLUSH PRIVILEGES;

CREATE USER IF NOT EXISTS 'matt'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON DST_AIRLINES.* TO 'matt'@'%';
FLUSH PRIVILEGES;