apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: airlines
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306  # Port externe fixe
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: airlines
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: sanourith/mysqlairlines:latest
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_USER
          value: "sanou"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "DST_AIRLINES"
        - name: MYSQL_HOST
          value: "0.0.0.0"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        resources: {}
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
