replicaCount: 1

image:
  repository: sanourith/mysqlairlines
  tag: "latest"
  pullPolicy: IfNotPresent

mysql:
  database: DST_AIRLINES

service:
  name: mysql-db
  type: NodePort
  port: 3306

persistence:
  enabled: true
  size: 2Gi
  storageClass: standard

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"
